### ISSUE TITLE
How to launch the sample?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [gabdube/panic-panda#1]
I tried to launch this "panic-panda.exe" , as I wanted to see Vulkan in action on my PC, but then I got this:

![image](https://user-images.githubusercontent.com/5357526/50785761-4b6a8580-12ba-11e9-841e-475c6a961fca.png)

**Comment by gabdube** [comment]
Looks like there is a problem in my code. There was no way to see the traceback, so I just reuploaded the frozen binaries. Can you run `panic-panda-x86_64-debug-standalone.zip` from https://github.com/gabdube/panic-panda/releases and post here the content of `run_log.txt`?  

Also, if you have https://www.lunarg.com/vulkan-sdk/ installed on your system, the traceback will pretty much pinpoint exactly why things went wrong. But that's not required.

**Comment by AndroidDeveloperLB** [comment]
Attached, but this time instead of showing the dialog I've shown you, it just opens and closes.

[run_log.txt](https://github.com/gabdube/panic-panda/files/2734531/run_log.txt)

**Comment by gabdube** [comment]
Thank you! You have a DEVICE_LOST error, which is the worst possible error for me to debug. Basically, something in my code crashes your vulkan driver. But there's no way to know exactly what without using the debugging layers from the lunarg sdk.

Are you using an intel/nvidia GPU by any chances? Because I can't test on these. I'd have to borrow somebody else computer which might take some times.

**Comment by AndroidDeveloperLB** [comment]
Shouldn't Vulkan be cross platform?
My specs:

![image](https://user-images.githubusercontent.com/5357526/50798906-ac0db880-12e2-11e9-93d1-f5cdfb88a770.png)

**Comment by gabdube** [comment]
Yes Vulkan is cross platform, but each vendor driver implementation behave differently. I was only using the most basic features, but I guess that doesn't save me from having to test on different hardware. I'll update this thread as soon as I find something.

**Comment by AndroidDeveloperLB** [comment]
Too bad. I wonder what the sample will show me though...

**Comment by gabdube** [comment]
Am I the fastest bug fixer in the west? Probably not, but I've managed to replicate the bug on a 1080 and it turns out it's a padding bug in the uniforms. I've released a hotfix in the release section. You should check it out.

**Comment by AndroidDeveloperLB** [comment]
Works fine now. Nice.
